# The site title, used for pages with a title and in RSS feeds.
title: "Rob (is no longer) in Europe"
# The (absolute) URL at which the site can be found (e.g., used in RSS feeds).
url: "http://rob-in-europe.github.io"
# A brief description of the site (e.g., used in RSS feeds).
description: ""

# Don't publish the README or LICENSE.
exclude: ['README.md', 'LICENSE']

# Support relative links for project pages on github and when serving the
# site locally, as per https://github.com/mojombo/jekyll/issues/332.
# For example, set to "/project-name" (without a trailing slash).
baseurl: ""

# The default colour theme for every page and post.
css_theme: "solarized-light"
# Define a theme name and URL to have a link appear in the page footer.
css_theme_name: "solarized"
css_theme_url: "http://ethanschoonover.com/solarized"
# Generate compact CSS files.
sass:
    style: compressed

# The URLs for site-wide files such as stylesheets.
url_css: "/assets/css"
url_img: "/assets/images"
url_js: "/assets/js"
url_data: "/assets/data"

# The URL for MathJax (hosted by cdnjs).
url_mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js"

# Set to "/some/path" if the blog is hosted in a sub-directory of this site.
url_blog: ""

# The URL for each blog post, as per http://jekyllrb.com/docs/permalinks/.
permalink: /:categories/:year/:month/:day/:title

# The time zone for site generation and identifying future posts.
timezone: "Australia/Melbourne"

# Links that appear in the navigation bar.
navlinks:
  - Home:
      url: "/"
      img: "home.png"
  - Travel:
      url: "/travel"
      img: "travel.png"
  - Recipes:
      url: "/recipes"
      img: "recipes.png"
  - French:
      url: "/french"
      img: "french.png"
  - Misc:
      url: "/misc"
      img: "misc.png"

# Set default layouts and navigation IDs, based on:
# http://stackoverflow.com/a/23555679
# Note that the range of values for "type" have changed since Jekyll 2.2;
# valid values are: "pages", "posts", "drafts", and any collection.
# See https://jekyllrb.com/docs/configuration/ for details.
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: "posts" # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      is_post: false
      layout: "site"
      archive_url: "date"
  -
    scope:
      path: "date"
    values:
      navid: "Home"
      blurb: "home"
  -
    scope:
      path: "tag"
    values:
      navid: "Home"
      blurb: "home"
  -
    scope:
      path: "french"
    values:
      navid: "French"
      category: "french"
      blurb: "french"
  -
    scope:
      path: "misc"
    values:
      navid: "Misc"
      category: "misc"
      blurb: "misc"
  -
    scope:
      path: "recipes"
    values:
      navid: "Recipes"
      category: "recipes"
      blurb: "recipes"
  -
    scope:
      path: "travel"
    values:
      navid: "Travel"
      category: "travel"
      blurb: "travel"

# Whether to display previous post and next post links for each post.
show_prev_next: true
# The number of posts to show when using the `posts_by_category` layout.
max_posts: 3
# The number of posts to include in the RSS feed.
feed_posts: 10
# Whether to display posts with dates in the future.
future: false

# The local server port to use when serving the site locally.
port: 4000
# Disable custom plugins.
safe: true

# Use kramdown because it correctly interprets LaTeX mathematics notation.
markdown: kramdown

# The default license under which a post is published.
default_license: CC BY-SA

# The list of licenses under which a post can be published.
licenses:
  - name: CC BY
    url: http://creativecommons.org/licenses/by/4.0/
    img: http://i.creativecommons.org/l/by/4.0/80x15.png
  - name: CC BY-SA
    url: http://creativecommons.org/licenses/by-sa/4.0/
    img: http://i.creativecommons.org/l/by-sa/4.0/80x15.png
  - name: CC BY-NC
    url: http://creativecommons.org/licenses/by-nc/4.0/
    img: http://i.creativecommons.org/l/by-nc/4.0/80x15.png
  - name: CC BY-NC-ND
    url: http://creativecommons.org/licenses/by-nc-nd/4.0/
    img: http://i.creativecommons.org/l/by-nc-nd/4.0/80x15.png
  - name: CC BY-NC-SA
    url: http://creativecommons.org/licenses/by-nc-sa/4.0/
    img: http://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png
  - name: CC BY-ND
    url: http://creativecommons.org/licenses/by-nd/4.0/
    img: http://i.creativecommons.org/l/by-nd/4.0/80x15.png
